[build]
  functions = "netlify/functions"
  publish = "." # Or the directory where your static files are (e.g., "public")

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
